#!/usr/bin/env bash

set -euo pipefail

cd "$(dirname "$0")/.."
out="THIRD_PARTY_LICENSES"
pylic="pywasm/dist/licenses"

# The embedded Python runtime is not a Go module, so `go list` below cannot see
# it. Its license texts are collected by pywasm/Dockerfile and committed
# alongside the artifact they cover; a dist tree without them would produce a
# notice file that silently omits everything CPython brings.
if [ ! -d "$pylic" ] || [ -z "$(find "$pylic" -name '*.txt' -print -quit)" ]; then
  echo "error: no license texts in $pylic — rerun 'make python-wasm'" >&2
  exit 1
fi

mods=$(go list -deps -f '{{with .Module}}{{.Path}}{{end}}' ./cmd/sbsh \
  | grep -v '^$' \
  | grep -v '^github.com/mrtc0/sbsh' \
  | sort -u)

{
  echo "sbsh — Third-Party Software Licenses"
  echo
  echo "sbsh itself is licensed under the MIT License (see the bundled LICENSE file)."
  echo "Distributions include the third-party software listed below, each governed by"
  echo "the terms of its original license."
  echo
  echo "Generated by scripts/gen-third-party-licenses.sh. Do not edit by hand."
  echo
} > "$out"

for m in $mods; do
  dir=$(go list -m -f '{{.Dir}}' "$m")
  ver=$(go list -m -f '{{.Version}}' "$m")
  echo "================================================================================" >> "$out"
  echo "$m $ver" >> "$out"
  echo "================================================================================" >> "$out"
  echo >> "$out"
  for f in LICENSE LICENSE.txt LICENSE.md COPYING NOTICE PATENTS; do
    if [ -f "$dir/$f" ]; then
      echo "--- $f ---" >> "$out"
      cat "$dir/$f" >> "$out"
      echo >> "$out"
    fi
  done
done

# CPython and everything linked into python.wasm. pywasm/embed.go compiles the
# whole tree into the binary, so an sbsh distribution is a CPython distribution,
# and the PSF License requires its License Agreement and copyright notice to be
# retained. The texts come from the same dist tree the binary embeds, so they
# describe the artifact actually shipped rather than whatever upstream holds now.
{
  echo "================================================================================"
  echo "Embedded Python runtime (pywasm/dist)"
  echo "================================================================================"
  echo
  echo "pywasm/dist/python.wasm and the standard library tree beside it are build"
  echo "outputs of pywasm/Dockerfile, embedded into the sbsh binary. Versions:"
  echo
  sed 's/^/  /' pywasm/dist/PROVENANCE
  echo
} >> "$out"

for f in "$pylic"/*.txt; do
  echo "--- $(basename "$f") ---" >> "$out"
  cat "$f" >> "$out"
  echo >> "$out"
done

echo "Wrote $out ($(grep -c . "$out") non-empty lines)"
